class AppStrings {
  static Map<String, Map<String, String>> _strings = {
    'pt': {
      'settings': 'Configurações',
      'profile': 'Meu Perfil',
      'myEvents': 'Meus Eventos',
      'notifications': 'Notificações',
      'privacy': 'Privacidade',
      'preferences': 'Preferências',
      'language': 'Idioma',
      'personalData': 'Dados Pessoais',
      'permissions': 'Permissões',
      'camera': 'Câmera',
      'location': 'Localização',
      'allowed': 'Permitido',
      'denied': 'Negado',
      'save': 'Salvar',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'fullName': 'Nome Completo',
      'newPassword': 'Nova Senha',
      'changePassword': 'Alterar Senha',
    },
    'en': {
      'settings': 'Settings',
      'profile': 'My Profile',
      'myEvents': 'My Events',
      'notifications': 'Notifications',
      'privacy': 'Privacy',
      'preferences': 'Preferences',
      'language': 'Language',
      'personalData': 'Personal Data',
      'permissions': 'Permissions',
      'camera': 'Camera',
      'location': 'Location',
      'allowed': 'Allowed',
      'denied': 'Denied',
      'save': 'Save',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'fullName': 'Full Name',
      'newPassword': 'New Password',
      'changePassword': 'Change Password',
    },
    'es': {
      'settings': 'Configuraciones',
      'profile': 'Mi Perfil',
      'myEvents': 'Mis Eventos',
      'notifications': 'Notificaciones',
      'privacy': 'Privacidad',
      'preferences': 'Preferencias',
      'language': 'Idioma',
      'personalData': 'Datos Personales',
      'permissions': 'Permisos',
      'camera': 'Cámara',
      'location': 'Ubicación',
      'allowed': 'Permitido',
      'denied': 'Denegado',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'fullName': 'Nombre Completo',
      'newPassword': 'Nueva Contraseña',
      'changePassword': 'Cambiar Contraseña',
    },
  };

  static String get(String key, String locale) {
    return _strings[locale]?[key] ?? _strings['pt']?[key] ?? key;
  }
}